name: CI
on:
  pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2

      # Set up Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Make Gradle wrapper executable
      - name: Make Gradle wrapper executable
        working-directory: PROG_DISTRIB/TP_DOCKER/rent
        run: chmod +x gradlew

      # Build and test
      - name: Build and test
        working-directory: PROG_DISTRIB/TP_DOCKER/rent
        run: |
          export SHELL=/bin/bash
          ./gradlew build --info

      # Build Docker image
      - name: Docker images
        working-directory: PROG_DISTRIB/TP_DOCKER/rent
        run: |
          export SHELL=/bin/bash
          docker build -t rent .
          docker images