name: CI
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: build
    steps:
      - uses: actions/checkout@v2
      - name: Make Gradle wrapper executable
        working-directory: PROG_DISTRIB/TP_DOCKER/rent
        run: chmod +x gradlew
      - name: Build and test
        working-directory: PROG_DISTRIB/TP_DOCKER/rent
        run: |
          export SHELL=/bin/bash
          ./gradlew build --info
      - name: Docker images
        working-directory: PROG_DISTRIB/TP_DOCKER/rent
        run: |
          export SHELL=/bin/bash
          docker build -t rent .
          docker images